# credentials:
#   usernames:
#     admin:
#       email: admin@company.com
#       name: Administrator
#       password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW  # admin@123
#     manager:
#       email: manager@company.com
#       name: Sales Manager
#       password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW  # manager@2024
#     viewer:
#       email: viewer@company.com
#       name: Sales Viewer
#       password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW  # view@789

# cookie:
#   expiry_days: 30
#   key: some_signature_key
#   name: tally_cookie

# preauthorized:
#   emails:
#     - admin@company.com